export * from './Layout';
export * from './Home';
export * from './Tours';
export * from './Destinations';
export * from './NotFound';
export * from './About';
export * from './FAQ';
export * from './Contact';
export * from './Legal';
