export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  BLOG: '/blog',
  TOURS: '/tours',
  DESTINATIONS: '/destinations',
  CONTACT: '/contact',
  FAQ: '/faq',
  LEGAL: '/terms-and-conditions',
  NEWSLETTER_CONFIRM: '/newsletter/verify',
  AUTH: '/auth',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  PROFILE: '/profile',
  PROFILE_FAVORITES: '/profile/favorites',
  PROFILE_BOOKINGS: '/profile/bookings',
  PROFILE_INFO: '/profile/info',
  NOT_FOUND: '*',
};
