export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  BLOG: '/blog',
  TOURS: '/tours',
  DESTINATIONS: '/destinations',
  CONTACT: '/contact',
  FAQ: '/faq',
  LEGAL: '/terms-and-conditions',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  PROFILE: '/profile',
  PROFILE_WISHLISTS: '/profile/wishlists',
  PROFILE_BOOKINGS: '/profile/bookings',
  PROFILE_INFO: '/profile/info',
  NOT_FOUND: '*',
};
